//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeo.Drivers.Plex {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class PlexSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlexSettings defaultInstance = ((PlexSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlexSettings())));
        
        public static PlexSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
